<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Baobab SharedKernel Presentation</Title>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Asp.Versioning.Mvc" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Baobab.SharedKernel.Infrastructure\Baobab.SharedKernel.Infrastructure.csproj" />
  </ItemGroup>

</Project>
